### PR TITLE
Add the support for Android Q

### PR DESCRIPTION
**Pull request by sophy228**

### CODE REVIEW

**Comment by sophy228** [comment]
@krnlyng  Thanks very much for your work and help. I just verified it on Intel X86-64 platform since I don't have ARM environment at all. 

And you also solved confusing problem of crashes on exit. Though I am still not clear that why g_default_namespace related modifications can solve it. :)

**Comment by sophy228** [comment]
@krnlyng  I have included your patches in such pull request but with two small reverting.

Especially for TLS_SLOT_BIONIC_TLS modification,  It is must at least on my X86-64 devices. Otherwise it crash when bionic lib try to call __get_bionic_tls()

**Comment by krnlyng** [comment]
@sophy228 we usually disable tls in bionic, for example:
https://github.com/mer-hybris/android_bionic/commit/78b481612c531f99d4b5c8848ec59063cef5aefe
is it not possible in this case? Otherwise i will have to test this with an actual android 10 device, might be that it's required there on arm too.

We don't have the autoconf-archive package in our system that's why i temporarily removed it.. but adding it is an easy solution for that :).

**Comment by sophy228** [comment]
@krnlyng  well I checked the codes about Q, the USE_TLS_SLOT seems not related to __get_bionic_tls(). it only appears in locale.cpp

and such function is also different on P. on P it uses the slot 0 and on Q it uses slot 9. I guess slot0 has been initialized by glibc but slot 9 doesn't.

**Comment by krnlyng** [comment]
@sophy228 ok i wasn't aware of that. maybe we should have the slot 9 then on both arm and x86. because if it's on an actual android 10 device with android 10 libc it might be required also on arm.

**Comment by sophy228** [comment]
@krnlyng  yes, now TLS_SLOT_BIONIC_TLS will be initialized when  (ANDROID_VERSION_MAJOR >= 10)

**Comment by Thaodan** [comment]
@sophy228 Are you rebasing hybris-patches too? currently bionic needs to be patched to have tls moved for forward to don't conflict with hybris. But the mechanism how tls slot work has changed and I'm stuck rebasing the hybris patches for bionic.

https://github.com/aosp-mirror/platform_bionic/commit/1e660b70da625fcbf1e43dfae09b7b4817fa1660

**Comment by sophy228** [comment]
@Thaodan sorry I am not familiar with TLS mechanism, so I had to disable functions in linker_tls.cpp you can check  patches above. But it seems that it still can work ....

But there are two problems, one is we discussed above  __get_bionic_tls() use tls slot 9,  so I initialized it in linker_main.cpp

another is that glibc for i386 will use slot 3 to store vsyscall return address, but bionic will use it to store openGL hooks. So all above can't work on i386..

**Comment by krnlyng** [comment]
@sophy228 would something like this help in your case:

https://github.com/mer-hybris/android_bionic/commit/8bd8f3cafb1bd147f167d87f885ee93a6b58bb01
https://github.com/mer-hybris/android_bionic/commit/a42af37d37859bc4b599c27d553da37ab1efa22e

?

**Comment by Thaodan** [comment]
@sophy228 I rebased hybris patches for Q. Maybe you can test them. Especially the TLS handling on x86_64.
https://github.com/Thaodan/hybris-patches/tree/hybris-sony-aosp-10

**Comment by Thaodan** [comment]
https://github.com/Thaodan/libhybris/commit/04affa6dcd763c02a6f52edd91f18b3505669ee0

**Comment by sophy228** [comment]
@Thaodan  Thanks very much ！ I will have a look and try!

**Comment by Thaodan** [comment]
@sophy228 Did you made some changes to bionic?
I get this error during building:
```
[100% 2/2] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: bionic/linker/Android.bp:1:1: module "liblinker_malloc" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:1:1 <-- previous definition here
error: bionic/linker/Android.bp:27:1: module "linker_wrapper" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:27:1 <-- previous definition here
error: bionic/linker/Android.bp:68:1: module "linker_sources" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:68:1 <-- previous definition here
error: bionic/linker/Android.bp:94:1: module "linker_sources_arm" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:94:1 <-- previous definition here
error: bionic/linker/Android.bp:102:1: module "linker_sources_arm64" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:102:1 <-- previous definition here
error: bionic/linker/Android.bp:110:1: module "linker_sources_x86" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:110:1 <-- previous definition here
error: bionic/linker/Android.bp:117:1: module "linker_sources_x86_64" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:117:1 <-- previous definition here
error: bionic/linker/Android.bp:124:1: module "linker_sources_mips" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:124:1 <-- previous definition here
error: bionic/linker/Android.bp:132:1: module "linker_sources_mips64" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:132:1 <-- previous definition here
error: bionic/linker/Android.bp:140:1: module "linker_version_script" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:140:1 <-- previous definition here
error: bionic/linker/Android.bp:145:1: module "linker_version_script_arm" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:145:1 <-- previous definition here
error: bionic/linker/Android.bp:150:1: module "linker_defaults" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:150:1 <-- previous definition here
error: bionic/linker/Android.bp:232:1: module "linker" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:232:1 <-- previous definition here
error: bionic/linker/Android.bp:310:1: module "ld-android" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:310:1 <-- previous definition here
error: bionic/linker/Android.bp:377:1: module "linker-unit-tests" already defined
       droid-hal-sony-kumano/hybris/mw/libhybris/libhybris/hybris/common/q/Android.bp:377:1 <-- previous definition here
15:56:07 soong bootstrap failed with: exit status 1
```

**Comment by krnlyng** [comment]
@Thaodan that's because the linkers Android.bp is in both libhybris and bionic repos since the linker is a copy. the android.bp in libhybris for the linker needs to be removed to avoid this, (sorry i forgot about that).

File: hybris/tests/Makefile.am [hunk 1]
```diff
@@ -16,7 +16,18 @@ bin_PROGRAMS = \
...
+test_dlopen_CFLAGS = \
+	-I$(top_srcdir)/include \
+	-I$(top_srcdir)/hybris/include \
+	-I$(top_srcdir)/include/android
+test_dlopen_LDADD = \
+	$(top_builddir)/common/libhybris-common.la \
+	$(top_builddir)/hardware/libhardware.la
 
 test_audio_SOURCES = test_audio.c
 test_audio_CFLAGS = \
```
Comment (Thaodan) [inline hybris/tests/Makefile.am]: Adding C99 here was needed for me to fix building

**Comment by krnlyng** [comment]
@sophy228 
can you address the above comments? (removing Android.bp and @Thaodan s comments)

also we should verify that all of the changes we applied to the n/o linkers are also applied to the q linker
e.g.: https://github.com/libhybris/libhybris/commits/master/hybris/common/o

after that i think this can be merged. thanks :)

**Comment by Thaodan** [comment]
@krnlyng  He could reuse my android q branch, I added some fixes for the build system there:
https://github.com/Thaodan/libhybris/commits/android_q

File: hybris/egl/platforms/common/support.h [hunk 2]
```diff
@@ -11,7 +11,7 @@
  *
  */
 #define container_of(ptr, type, member) ({			\
-	const typeof( ((type *)0)->member ) *__mptr = (ptr);	\
+	const decltype( ((type *)0)->member ) *__mptr = (ptr);	\
```
[the remark this answers is not in the document]
Comment (sophy228) [reply hybris/egl/platforms/common/support.h]: libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../.. -I/home/android_head/ -I../../../include -I../../../egl -I/home/android_head/ -I../../../common/ -I/usr/local/include -I/usr/local/include -I/home/and
roid_head/ -ggdb -O0 -g -O2 **-std=c++14** -MT libhybris_eglplatformcommon_la-server_wlegl_buffer.lo -MD -MP -MF .deps/libhybris_eglplatformcommon_la-server_wlegl_buffer.Tpo -c server_wlegl_buffer.cpp  -fPIC 
-DPIC -o .libs/libhybris_eglplatformcommon_la-server_wlegl_buffer.o
In file included from nativewindowbase.cpp:13:0:
nativewindowbase.cpp: In static member function 'static void BaseNativeWindowBuffer::_decRef(android_native_base_t*)':
support.h:14:14: error: ISO C++ forbids declaration of 'typeof' with no type [-fpermissive]
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \


Because I met this error, did not you ?  It is strange that my ISO C++ can't recognize typeof but yours can't recognize decltype

[the remark this answers is not in the document]
Comment (sophy228) [reply hybris/egl/platforms/common/support.h]: After I searched some article, I think we should used the decltype instead of typeof.

Could you please show your gcc/g++ version ?
here is mine
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

File: hybris/tests/Makefile.am (hunk 1 above)
Comment (sophy228) [reply hybris/tests/Makefile.am]: I also have no issue.
Could you please show the error message ?

**Comment by sophy228** [comment]
@krnlyng  Thanks for reminder, and I add a new patch to remove the Android.bp file.
And for other changes on n/o,  could you please also help ?  For example, I disabled the gdb in Q since I found it will cause memory leak and crash when enable it. I may be lack of experience to handle this.

File: hybris/egl/platforms/common/support.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (Thaodan) [reply hybris/egl/platforms/common/support.h]: Because typeof is a gcc extension. You need to use -std=gnu++11. The GCC in Sailfish is currently is GCC 4.9

File: hybris/tests/Makefile.am (hunk 1 above)
Comment (Thaodan) [reply hybris/tests/Makefile.am]: Without the -std=c99 flag c89 is used here which doesn't  allow the initialization of variables inside the loop

https://stackoverflow.com/questions/1287863/c-for-loop-int-initial-declaration

Comment (sophy228) [reply hybris/tests/Makefile.am]: Well, even I have add the c89 manually , I can still build it successfully.
gcc -DHAVE_CONFIG_H -I. -I..   -I/home/android_head/ -I../include -I../hybris/include -I../include/android -g -O2 **-std=c89** -MT test_dlopen-test_dlopen.o -MD -MP -MF .deps/test_dlopen-test_dlopen.Tpo -c -o test_dlopen-test_dlopen.o `test -f 'test_dlopen.c' || echo './'`test_dlopen.c

Maybe I need to downgrade my GCC? Since I can't reproduce your two issues at all.

File: hybris/egl/platforms/common/support.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (sophy228) [reply hybris/egl/platforms/common/support.h]: but in configure.ac I add this:
AX_CHECK_COMPILE_FLAG([-std=c++14], [CXXFLAGS="$CXXFLAGS -std=c++14"])

So every thing should be built with -std=c++14

And why the "decltype" doesn't work in your environment even with C++14?

File: hybris/tests/Makefile.am (hunk 1 above)
Comment (Thaodan) [reply hybris/tests/Makefile.am]: The comment was about the audio test not the dlopen test.

File: hybris/egl/platforms/common/support.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (Thaodan) [reply hybris/egl/platforms/common/support.h]: GCC 4.9 doesn't support C++14 so you can't use that here.

File: hybris/tests/Makefile.am (hunk 1 above)
Comment (Thaodan) [reply hybris/tests/Makefile.am]: The audio header from android q includes a loop that uses c99 style loops.

**Comment by Thaodan** [comment]
Please apply my build system fixes to this PR as mentioned.

**Comment by sophy228** [comment]
> Please apply my build system fixes to this PR as mentioned.

OK @Thaodan  https://github.com/Thaodan/libhybris/commits/android_q
Which commits are your fixex for this ？ I can apply it to this PR.

**Comment by Thaodan** [comment]
The last 3 are the commits that you need, I rebased my branch just merge my branch.
Also you need to revert the C++14 stuff as Sailfish OS doesn't support it. Maybe @krnlyng  can say you more about this.

**Comment by Thaodan** [comment]
You can use  git rebase --
interactive to kill the C++14 
related commits.

**Comment by coltorchen** [comment]
any updates about this PR,it seems not merged to the repo?

File: hybris/common/q/linker_main.cpp [hunk 3]
```diff
@@ -0,0 +1,844 @@
...
+    PRINT("can't prelink self:ret\n");
+  };
+
+  //tmp_linker_so.call_constructors();
+}
+
+#if (ANDROID_VERSION_MAJOR >= 10)
+bionic_tls* __allocate_temp_bionic_tls() {
+  size_t allocation_size = __BIONIC_ALIGN(sizeof(bionic_tls), PAGE_SIZE);
+  void* allocation = mmap(nullptr, allocation_size,
```
[the remark this answers is not in the document]
Comment (coltorchen) [reply hybris/common/q/linker_main.cpp:768]: > > any updates about this PR? it seems not merged to the repo?
> 
> I am not aware of anybody having successfully brought up UI with this, which i would see as a requirement.
> Also there is still the question about the TLS variables.
> 
> EDIT: sorry, apparently the question was only submitted right now since i forgot to press "submit review"... (see below)

i just want to have a try, make PostMarket OS with libhybris -Android 10.0  supported.

**Comment by coltorchen** [comment]
> > any updates about this PR? it seems not merged to the repo?
> 
> I am not aware of anybody having successfully brought up UI with this, which i would see as a requirement.
> Also there is still the question about the TLS variables.
> 
> EDIT: sorry, apparently the question was only submitted right now since i forgot to press "submit review"... (see below)

i just want to have a try, make PostMarket OS with libhybris -Android 10.0 supported.

**Comment by coltorchen** [comment]
> > any updates about this PR? it seems not merged to the repo?
> 
> I am not aware of anybody having successfully brought up UI with this, which i would see as a requirement.
> Also there is still the question about the TLS variables.
> 
> EDIT: sorry, apparently the question was only submitted right now since i forgot to press "submit review"... (see below)

i just want to have a try, make PostMarket OS with libhybris -Android 10.0 supported.
and another question,how did you test this PR? it seems the hybris-patched not working Android 10.0 [()](https://github.com/Halium/hybris-patches)

**Comment by coltorchen** [comment]
> > any updates about this PR? it seems not merged to the repo?
> 
> I am not aware of anybody having successfully brought up UI with this, which i would see as a requirement.
> Also there is still the question about the TLS variables.
> 
> EDIT: sorry, apparently the question was only submitted right now since i forgot to press "submit review"... (see below)

i just want to have a try, make PostMarket OS with libhybris -Android 10.0 supported.
and another question,how did you test this PR? it seems the hybris-patched not working Android 10.0 [https://github.com/Halium/hybris-patches](url)

**Comment by coltorchen** [comment]
> > any updates about this PR? it seems not merged to the repo?
> 
> I am not aware of anybody having successfully brought up UI with this, which i would see as a requirement.
> Also there is still the question about the TLS variables.
> 
> EDIT: sorry, apparently the question was only submitted right now since i forgot to press "submit review"... (see below)

i just want to have a try, make PostMarket OS with libhybris -Android 10.0 supported.
and another question,how did you test this PR? it seems the hybris-patches not working on Android 10.0 https://github.com/Halium/hybris-patches

**Comment by xingyanan** [comment]
> @sophy228 I rebased hybris patches for Q. Maybe you can test them. Especially the TLS handling on x86_64.
> https://github.com/Thaodan/hybris-patches/tree/hybris-sony-aosp-10
@Thaodan i'm test your patch on android 10，compile get error. i did (./autogen.sh -> make) 
``dlfcn.c: At top level:
dlfcn.c:205:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
       st_value: (Elf_Addr) &android_dlopen,
                 ^
dlfcn.c:205:17: error: initializer element is not constant
dlfcn.c:205:17: note: (near initialization for 'libdl_symtab[1].st_value')
dlfcn.c:210:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
       st_value: (Elf_Addr) &android_dlclose,
                 ^
dlfcn.c:210:17: error: initializer element is not constant
dlfcn.c:210:17: note: (near initialization for 'libdl_symtab[2].st_value')
dlfcn.c:215:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
       st_value: (Elf_Addr) &android_dlsym,
                 ^
dlfcn.c:215:17: error: initializer element is not constant
dlfcn.c:215:17: note: (near initialization for 'libdl_symtab[3].st_value')
dlfcn.c:220:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
       st_value: (Elf_Addr) &android_dlerror,
                 ^
dlfcn.c:220:17: error: initializer element is not constant
dlfcn.c:220:17: note: (near initialization for 'libdl_symtab[4].st_value')

**Comment by sledges** [comment]
Thank you @sophy228.
We have used your commits and improved upon them to boot Sailfish OS on Xperia 10 II, the branch can be found [here](https://github.com/sledges/libhybris-upstream/tree/q-support) (rebased against master).

Feel free to use it in this PR and to polish it further.

**Comment by sophy228** [comment]
> Thank you @sophy228.
> We have used your commits and improved upon them to boot Sailfish OS on Xperia 10 II, the branch can be found [here](https://github.com/sledges/libhybris-upstream/tree/q-support) (rebased against master).
> 
> Feel free to use it in this PR and to polish it further.

You are welcome, and I have been leave Android area for about 1 year and mainly focus on Web Assembly  runtime now, so very glad to see you have made so much improvements and progress based on this PR.

**Comment by sledges** [comment]
> > Thank you @sophy228.
> > We have used your commits and improved upon them to boot Sailfish OS on Xperia 10 II, the branch can be found [here](https://github.com/sledges/libhybris-upstream/tree/q-support) (rebased against master).
> > Feel free to use it in this PR and to polish it further.
> 
> You are welcome, and I have been leave Android area for about 1 year and mainly focus on Web Assembly runtime now, so very glad to see you have made so much improvements and progress based on this PR.

Thank you again. I cannot push to this PR/branch, so I opened a new PR (#467) after receiving permission from libhybris maintainer. This PR could then be safely closed.
